project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    background: "primary"
    left:
    - text: "Home"
      file: index.qmd
    - text: "Valuation-Based Kelly Optimal Portfolios"
      file: KellyOptimalMarketCycles.qmd
    - text: "Log Optimal Portfolio and Option Pricing"
      menu:
      - text: "Part 1"
        file: logoptimal1.qmd
      - text: "Part 2"
        file: logoptimal2.qmd
      - text: "Part 3"
        file: logoptimal3.qmd
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-fold: true



