---
title: "About"
---

I am Drew Balkin, a PhD student in Mathematics with a deep interest in all things finance. I enjoy mixing the tools and techniques of quantitative finance with the traditional viewpoints of finance on fundamental valuation.

One of my personal goals is to use mathematics to model market phenomena based on fundamental principles that will result in a greater understanding of market dynamics.

## Academic Research

As for my background, I am completing my PhD in mathematics from UC Santa Barbara with a graduation date in September of 2023. In this time, I have studied machine learning methods for solving stochastic optimal control problems and stochastic differential games. You can view some of my papers below.

-   [Stochastic Delay Differential Games: Financial Modeling and Machine Learning Algorithms](https://arxiv.org/pdf/2307.06450.pdf) showcases a methodology to solve stochastic delay differential games with machine learning and highlights various financial problems that can be solved with this technique.

-   [Optimal Policies for a Pandemic: A Stochastic Game Approach and a Deep Learning Algorithm](https://msml21.github.io/papers/id42.pdf) models Covid-19 dynamics in a game theoretic setting whereby an individual region's policies interact with those of other regions. Deep learning techniques are used to find the Nash equilibrium for this problem. This paper was published in Proceedings of Machine Learning Research vol 145:1--26, 2021 2nd Annual Conference on Mathematical and Scientific Machine Learning.

-   [Pandemic Control, Game Theory, and Machine Learning](https://ams.org/journals/notices/202211/rnoti-p1878.pdf) provides a survey on stochastic control and differential games applied to Covid-19 as well as the deep learning techniques which allows for solutions to these difficult problems. This was featured in the American Mathematical Society (AMS) Notices.

## Blog Projects and Research

In this blog, I want to highlight some of my thoughts in a more accessible and informal manner. In part, some work is inspired by my academic research such as my blog post on [valuation based Kelly optimal portfolios for market cycle investing](./KellyOptimalMarketCycles.qmd). Some of the work in this blog is just my own personal excursion into financial math topics of great interest to me that are relatively uncovered in the financial literature. While the results are known if you are willing to dig deep, I show my own derivations of how the log-optimal portfolio can be used in option pricing in a surprisingly general manner (see the "Log Optimal Portfolio and Option Pricing" blog posts [part 1](./logoptimal1.qmd), [part 2](./logoptimal2.qmd), and [part 3](./logoptimal3.qmd)).

### Valuation-based Kelly Optimal Portfolios for Market Cycle Investing

From a rational standpoint, the value of an equity is the cumulative expected value of its discounted payouts (i.e dividends), where the discounting of dividends is not only done with respect to time, but also for its perceived risk. From this point of view, the movement of the market can be decomposed into two key noises:

1. Change in the (estimated) probability distribution of future dividends. 
2. Change in the discount factor for future dividends due to both changing interest rates as well as **changing risk-preferences**.

Therefore, from this rational point of view, market movement is not solely based on pricing in new economic developments, but also due to risk-preferences that vary throughout time. While even this rational view leads to changes in valuation due to changing risk preferences, this does not encapsulate the full reality of the stock market.

In reality, the flows into and out of the market are often non-fundamentally driven, i.e. without regard for valuation. While we can assume a large portion of wealth is allocated based on decisions that are more "behavioral" than rational, today's current market environment is full of non-fundamental flows beyond the "behavioral investor". Mandated allocation rules (pension funds), forced liquidations / untimely withdrawals (hedge funds), and systematic passive investing (retirement accounts) all contribute to flows that are completely valuation agnostic.

These two factors -- changing risk preferences and valuation-agnostic investing --  may lead to market cycles in valuation. 

Assuming this is true, how should one allocate over time given the existence of these market cycles?

I offer a very simple model to offer the start of a framework for this question. This model offers a teaching viewpoint for techniques that can be used in more sophisticated models. This work is included in my blog post on [Valuation-based Kelly Optimal Portfolios for Market Cycle Investing](./KellyOptimalMarketCycles.qmd).


### Log-Optimal Portfolio and Option Pricing

Traditionally, financial derivatives are priced as their discounted payout under a risk neutral measure. I was intrigued by an approach that I rediscovered that shows the price of the derivative is actually its payout under the physical measure when a certain unit of account (or numeraire) is considered. Specifically, if one takes as unit of account the so-called "log-optimal portfolio", then the option's price is exactly the expected value of the option's payout under the true physical measure! In other words, pricing a derivative/security/asset in units of log-optimal portfolio naturally discounts for risk and time! Not only is this true, but it can even be extended to more general frameworks.

While the results are known, I want to present this knowledge in a non-technical fashion for someone with a background in mathematical finance in the same way I rediscovered these results. Here are my lecture notes on this topic starting from [the basic case of a traditional Black-Scholes model](./logoptimal1.qmd) and then to [the case for a generalized market model ](./logoptimal2.qmd). In fact, we show this framework is even true for a [utility based pricing in the case of unattainable claims](./logoptimal3.qmd)! 

