---
title: "Log-Optimal Numeraire for Unattainable Claims"
---


What we will now show is a very interesting result regarding the pricing under the log-optimal numeraire. So far, we have shown for a very general model, that the pricing

$$
\Pi(t;X) = \mathbb{E}^\mathbb{P} \left[ \frac{X}{V^{\pi^*}_T/V^{\pi^*}_t} \Bigg| \mathcal{F}_t \right]
$$ holds for all attainable claims $X$ where $\pi^*$ is the log-optimal portfolio process and $V^{\pi^*}$ its corresponding portfolio value. This exciting results means that the naive pricing can be done under the physical measure $\mathbb{P}$ as long as we were denoting everything to be in the "right" units of "currency" (or numeraire) -- which happens to be the log-optimal portfolio value.

Although an exciting result, there are two main problems this faces for practical implementation. The first is that it is actually hard to achieve the growth optimal portfolio as one would have to know the local rates of mean return, volatilities (across all differing possible sources of noise), and money market rate -- $\mu_t$, $\sigma_t$, $r_t$ at each time. Although these values are themselves random, the model we consider (a generalization of Black-Scholes, local volatility, stochastic volatility, and much else) still assumes that at time $t$ we know what those values are at that instant (although we don't know the resulting shocks due to the noise). Specifying the "ground truth" (random) model is very, very hard in reality!

We will not address this first problem that corresponds to its limited viability in reality. Instead we will deal with a secondary problem. What we have shown so far is a pricing for attainable claims. For unattainable claims (ones we cannot hedge), we may still find a derivative (long or short) compelling based on the price. Thus although one cannot hedge the option, one can still assign their personal value to the option. If going long/short the option (at the observed price) can increase the expected utility of their portfolio, then the investor will buy/sell the option. 

Using utility theory, it is very easy to understand when the investor gains from buying or selling the option. Suppose $\pi$ is the optimal portfolio (among presently traded securities) for an investor with utility function $U$. All of a sudden, an option $\chi$ comes on the market. The option will payout $\chi_T$ at time $T$ and can be bought/sold for $\chi_0$. Without loss of generality, assume $V^\pi_0 = 1$. The investor will be interested (in a small amount) of the option if the initial price $\chi_0$ is such that their expected utility increases by adding a tiny position (long option) to the portfolio. If the option price is such that their expected utility decreases by adding a small amount of long option, then we can show the investor would be interested in the short option position. Thus, we can find the personal price for a given investor of the option as the price such that they are indifferent to adding a small amount of option to their portfolio.

# Indifference Pricing for all CRRA Utilities

We will now compute the marginal utility indifference price for all CRRA investors. This means that an investor has the utility of the form

$$U(x) = \gamma x^ \gamma$$

for some $\gamma < 1$. This is an arbitrary CRRA utility function. While this seems restrictive, this is a general utility function for the class of investor's who decide on lotteries based purely on return outcomes and not absolute wealth levels. 

Assume that an investor currently has an optimal portfolio strategy for their utility function. This gives wealth process $V^{\pi_\gamma}_T$. Without loss of generality, assume $V^{\pi_\gamma}_0 = 1$.

Now consider a claim with payout at time $T$, $\chi_T$. We denote its value (to investor with utility indexed by $\gamma$) at time $0$ by $\chi_0(\gamma)$.

Assuming the investor now allocates $\epsilon$ of their wealth to $\chi$ and $(1-\epsilon)$ to their original ($\gamma$ - utility optimal) strategy, then the investor will be indifferent to adding the option if

$$\frac{d}{d\epsilon} \Bigg|_{\epsilon = 0} \mathbb{E} \left[ U\left((1-\epsilon)V^{\pi_\gamma}_T + \epsilon \frac{\chi_T}{\chi_0}\right)\right] = 0.$$

What this means is that the investor does not gain any expected utility by adding/ removing $\chi$ to their portfolio. In otherwords, they are indifferent to buying or selling the option. What we notice is that whether the above will hold or not depends on the initial price of the option $\chi_0$. Thus we call $\chi_0(\gamma)$ to be the marginal utility indifference price of the option for investor with risk preference parameter $\gamma$. It turns out we can solve for $\chi_0(\gamma)$ by taking the derivative and using the linearity of the expectation. Doing this, we get

$$\chi_0(\gamma) = \frac{\mathbb{E} \left[ U'(V^{\pi_\gamma}_T) \chi_T \right]}{\mathbb{E} \left[ U'(V^{\pi_\gamma}_T) V^{\pi_\gamma}_T\right]},$$

where the expectation is under $\mathbb{P}$. We can write this very suggestively as:

$$
\chi_0(\gamma) = \mathbb{E}[ m_T(\gamma) \chi_T ] 
$$ by taking $$m_T(\gamma) =  \frac{U'(V^{\pi_\gamma}_T)}{\mathbb{E} \left[ U'(V^{\pi_\gamma}_T) V^{\pi_\gamma}_T \right]}.$$

Thus we have found the natural stochastic discount factor for an investor with a given utility function. This is interesting, but we are just getting started.

Note we have for investor with CRRA utility and risk preference parameter $\gamma$ that

$$\chi_0(\gamma) = \frac{\mathbb{E}^\mathbb{P} \left[ U'(V^{\pi_\gamma}_T) \chi_T \right]}{\mathbb{E}^\mathbb{P} \left[ U'(V^{\pi_\gamma}_T) V^{\pi_\gamma}_T\right]}.$$

We know that if the investor has the log utility $\gamma = 0$, then we will have $U'(V^{\pi^*}_T) = \frac{1}{V^{\pi^*}_T}$ so we get the result that we previously knew:

$$
\chi_0(0) = \mathbb{E}^\mathbb{P} \left[ \frac{\chi_T}{V^{\pi^*}_T} \right].$$

That's exciting!!! But wait... not really. Not everyone is a log utility investor as they could have different risk preferences. In reality, not everyone is a CRRA investor either, but it is a good approximation for fund managers who are focused on performance in terms of returns.

# The Big Result

We haven't yet used the CRRA utility property. What we will show is that for  is for all CRRA investors, we have that $\chi_0(\gamma) = \chi_0(0)$. That is the indifference price is the same for all assets. Moreover, this indifference price is given by:

$$\chi_0(\gamma) = \mathbb{E} \left[\frac{\chi_T}{V^{\pi^*}_T} \right],$$

where $V^{\pi^*}_T$ is the value process at time $T$ for the log-optimal portfolio. This is the same result we had before for attainable claims!!!

Now, one big caveat is that this is the price for an infinitesimal quantity of the claim. This is because this indifference pricing argument found the initial price such that an investor would be indifferent to adding an infinitely small amount of said claim to their portfolio. We have not done an analysis on the indifference price for adding larger amounts of claims. The desired price the investor demands will differ if they already owned a substantial position in the derivative security.

I don't want to take away from this result either. We will show that the same pricing formula from [part 1](./logoptimal1.qmd) and [part 2](./logoptimal2.qmd) holds even for unattainable claims for the wide and realistic class of all CRRA investors, but only for an infinitely small amount of option.

# The Computation

As before, we assume the following model for $I$ risk assets driven by $J$ noises so as to get:

$$ \frac{dS^i_t}{S^i_t} = \mu^i_t dt + \sum_{j=J}^m \sigma^{ij}_t dW^j_t$$

with portfolio processes then given by 

$$\frac{dV^\pi_t}{V^\pi_t} = \sum_{i=1}^I \pi^i_t \frac{dS^i_t}{S^i_t}.$$
Notice how we are temporarily ignoring the money-market allocation and rate $r_t$. Actually, we can assume that we are (temporarily) in units of the cash-account numeraire i.e. everything is priced in units of $B_t$. This can be easily worked out. The main thing is that the asset local mean returns are understood now as $\mu^i_t - r_t$ (since they are discounted by the bank account). Also, $(\pi^i_t)$ need not add up to $1$ as the remaining amount is taken to be borrowings. If it makes one feel better, one can adjust the model to be the same one from [part 2](./logoptimal2.qmd) and carry out the future computations in terms of the model in terms of units of currency and not units of $B_t$. 

## Computation of the $\gamma$-Optimal Portfolio


Anyway, with this out of the way, we proceed by computing the optimal portfolios for investors with $\gamma$ risk preference parameter. Actually, we will show that like the log-utility maximization example from [part 1](./logoptimal1.qmd), the case of power utility can also be optimized in a very similar fashion in a way that avoids the usual approach of guessing solutions for the HJB equation!

We compute:

$$d \log((V^{\pi_\gamma}_t)^\gamma) = \gamma d \log(V^{\pi_\gamma}_t) =  \gamma\frac{dV^{\pi_\gamma}_t}{V^{\pi_\gamma}_t} - \frac{1}{2} \gamma \left(\frac{dV^{\pi_\gamma}_t}{V^{\pi_\gamma}_t} \right)^2.$$

This gives

$$ (V^{\pi_\gamma}_T)^\gamma = \exp \left[ \int_0^T \gamma \left(  \pi_t^T \mu_t -   \frac{1}{2} \pi_t^T \sigma_t \sigma_t^T \pi_t \right) dt + \int_0^T \gamma \pi_t^T \sigma_t d\vec{W}_t \right] .$$

as we are assuming all portfolio values are initial $1$. Multiplying by $\gamma$ and taking expectation, we get:

$$\mathbb{E}[U(V^{\pi_\gamma}_T)] = \mathbb{E}[\gamma (V^{\pi_\gamma}_T)^\gamma] = \gamma \mathbb{E} \left[ \exp \left( \int_0^T  \left(  \gamma \pi_t^T \mu_t -   (\frac{1}{2}\gamma - \frac{1}{2}\gamma^2)  \pi_t^T \sigma_t \sigma_t^T \pi_t \right) dt \right) \right].$$

Since $(\sigma_t\sigma_t^T)$ is invertible (this holds for arbitrage free models), we can optimize the integrand pointwise and the optimal portfolio occurs at 

$$ \pi^{\gamma,*}_t = \frac{1}{1-\gamma}(\sigma_t \sigma_t^T)^{-1} \mu_t.$$ 

To see why optimizing the integrand pointwise holds, define:

$$f(\pi_t(\omega) , \omega, t) =  \gamma \pi_t(\omega)^T \mu_t(\omega) -   (\frac{1}{2}\gamma - \frac{1}{2}\gamma^2)  \pi_t(\omega)^T \sigma_t(\omega) \sigma_t^T(\omega) \pi_t(\omega).$$

Note that $\gamma < 1$ and $\sigma \sigma^T$ is uniformly strictly positive definite by assumption, so by quadratic optimization, we have that $\pi^*_t(\omega) = \frac{1}{1-\gamma}(\sigma_t \sigma_t^T)^{-1} \mu_t$ is such that:

$$f(\pi_t(\omega),\omega,t) \leq f(\pi^*_t(\omega),\omega,t), \quad \forall (t, \omega).$$
Hence


$$\mathbb{E} \left[ e^{\int_0^T f (\pi_t(\omega),\omega,t) dt} \right] \leq \mathbb{E} \left[ e^{\int_0^T f(\pi^*_t(\omega),\omega,t) dt} \right].$$


Now that we know that the investor with risk preference parameter $\gamma$ has their optimal portfolio given by

$$ \pi^{\gamma,*}_t = \frac{1}{1-\gamma}(\sigma_t \sigma_t^T)^{-1} \mu_t.$$ 

Now, we call the corresponding wealth process $V^{\pi_\gamma}$ and compute the indifference price for this investor:

$$\chi_0(\gamma) = \frac{\mathbb{E} \left[ U'(V^{\pi_\gamma}_T) \chi_T \right]}{\mathbb{E} \left[ U'(V^{\pi_\gamma}_T) V^{\pi_\gamma}_T\right]}$$

and show it is the same for each $\gamma$.

## Computation of the $\gamma$-Investor's Utility Indifference Price

First, notice the CRRA utility satisfies $U'(V^{\pi_\gamma}_T) = \gamma \frac{U(V^{\pi_\gamma}_T)}{V^{\pi_\gamma}_T}$. This allows us to write:

$$\chi_0 = \frac{\mathbb{E} \left[ U(V^{\pi_\gamma}_T) \frac{\chi_T}{V^{\pi_\gamma}_T} \right]}{\mathbb{E} [ U(V^{\pi_\gamma}_T)]} = \mathbb{E} \left[ \frac{U(V^{\pi_\gamma}_T)}{\mathbb{E} [ U(V^{\pi_\gamma}_T)]} \frac{\chi_T}{V^{\pi_\gamma}_T} \right].$$

Next,

$$ V^{\pi_\gamma}_T = \exp \left[ \int_0^T\left(  \pi_t^T \mu_t -   \frac{1}{2} \pi_t^T \sigma_t \sigma_t^T \pi_t \right) dt + \int_0^T  \pi_t^T \sigma_t d\vec{W}_t \right] $$

where $\pi_t = \pi^{\gamma,*}_t =  \frac{1}{1-\gamma}(\sigma_t \sigma_t^T)^{-1} \mu_t$. So we have

$$ V^{\pi_\gamma}_T = \exp \left[ \int_0^T \frac{\frac{1}{2} - \gamma}{(1-\gamma)^2} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \mu_t dt + \int_0^T \frac{1}{1-\gamma} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \sigma_t d\vec{W}_t  \right] .$$

Next

$$ (V^{\pi_\gamma}_T)^\gamma = \exp \left[ \int_0^T \gamma \frac{\frac{1}{2} - \gamma}{(1-\gamma)^2} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \mu_t dt + \int_0^T \frac{\gamma}{1-\gamma} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \sigma_t d\vec{W}_t  \right] .$$

Therefore, using $$U(V^{\pi_\gamma}_T) = \gamma (V^{\pi_\gamma}_T)^\gamma $$ and simplifying the coefficients, we have

$$\frac{U(V^{\pi_\gamma}_T)}{\mathbb{E} [ U(V^{\pi_\gamma}_T)]} = \exp \left[ \int_0^T -\frac{1}{2}\left(\frac{\gamma}{1-\gamma} \right)^2 \mu_t^T (\sigma_t \sigma_t^T)^{-1} \mu_t dt + \int_0^T \frac{\gamma}{1-\gamma} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \sigma_t d\vec{W}_t  \right],$$

and thus

$$ \frac{U(V^{\pi_\gamma}_T)}{\mathbb{E} [ U(V^{\pi_\gamma}_T)]} \frac{1}{V^{\pi_\gamma}_T}   =   \exp \left[ \int_0^T \frac{-1}{2} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \mu_t dt - \int_0^T \mu_t^T (\sigma_t \sigma_t^T)^{-1} \sigma_t d\vec{W}_t  \right].$$

Hence the indifference price is then:

$$\chi_0 = \mathbb{E} \left[ \frac{U(V^{\pi_\gamma}_T)}{\mathbb{E} [ U(V^{\pi_\gamma}_T)]} \frac{\chi_T}{V^{\pi_\gamma}_T} \right] = \mathbb{E} \left[ \frac{\chi_T}{\exp \left[ \int_0^T \frac{1}{2} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \mu_t dt + \int_0^T \mu_t^T (\sigma_t \sigma_t^T)^{-1} \sigma_t d\vec{W}_t  \right]}  \right].$$

Lastly note that the log-optimal portfolio corresponds to

$$\pi^*_t = (\sigma_t \sigma_t^T)^{-1} \mu_t$$ and its corresponding portfolio process is $V^{\pi^*}_T = \exp \left[ \int_0^T \frac{1}{2} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \mu_t dt + \int_0^T \mu_t^T (\sigma_t \sigma_t^T)^{-1} \sigma_t d\vec{W}_t \right]$ as we are assuming all initial portfolio values are $1$.

Thus each CRRA investor has the indifference price:

$$\chi_0 = \mathbb{E} \left[ \frac{\chi_T}{\exp \left[ \int_0^T \frac{1}{2} \mu_t^T (\sigma_t \sigma_t^T)^{-1} \mu_t dt + \int_0^T \mu_t^T (\sigma_t \sigma_t^T)^{-1} \sigma_t d\vec{W}_t  \right]}  \right] = \mathbb{E} \left[ \frac{\chi_T}{V^{\pi^*}_T} \right],$$

*even* in the case of non-attainable claims.


