---
title: " Log-Optimal And Risk Neutral Valuation -- The Basics"
---

# Overview of Parts 1-3

I am assuming the reader is well-versed in stochastic calculus and knows the foundational results on arbitrage pricing of contingent claims. Those that are familiar are used to the risk-neutral valuation of an option -- that is the options price is just the expected value of its discounted payoff under the risk neutral measure. What I aim to do is illustrate a really nice result that allows one to price the option under the true physical measure. Rather than doing this with the given stochastic discount factor, we do it with a choice of numeraire induced by a portfolio. It turns out that the log-optimal portfolio is the unique portfolio such that the price of a claim is simply the expected value (under the physical measure) of the payout priced in units of log-optimal portfolio value! In other words, the growth of wealth process from the log-optimal portfolio appropriately discounts for time and risk such that pricing can be done under $\mathbb{P}$!

In this post, we will show that this holds for the typical Black-Scholes-Merton model of the market. Then we will show this result holds for all attainable claims for a general class of market models in [part 2 of this blog topic](./logoptimal2.qmd). 

While finding a consistent way to price attainable claims under $\mathbb{P}$ using the log-optimal portfolio as numeraire is indeed beautiful, we might say "so what? We already know how to price attainable claims!" Well, in [part 3 of this blog topic](./logoptimal3.qmd), we go one step further and price claims that are unattainable. You might say this is impossible! Indeed from the perspective of arbitrage pricing, it is impossible, as by definition one cannot hedge an unattainable claim. However, from the perspective of utility theory, there is a right "price" for each person. In fact, we will show that if one defines the price of a claim for a given person such that this person is indifferent to owning a small amount of claim at that price, then something spectacular happens: the price of the claim turns out to still be the expected payout (under $\mathbb{P}$) of the claim in units of log-optimal portfolio for all investors even with different (CRRA) risk preferences! So, from this perspective, pricing under the log-optimal portfolio generalizes option pricing whereby not only are the results consistent with hedgeable claims, but also for those that cannot be hedged as well!

I will say all of this turns out to not be anything new, but not much is said on this topic especially as one adds more and more generality. My derivations are that of my own and are meant to be simple. This was created by my own exploration and personal rediscovery of these results, and I am presenting my own past excursion in their derivation. My approach is meant to be simple. This means that there will be some simplifying assumptions that make life easier. You will see more on that later.


# Review

Let us review a couple of things from the standard Black-Scholes model in the simplest case of a single risky asset. For simplicity, we assume a constant risk free rate $r$ for the money market account with price process $(B_t)$, while the stock has a price process $(S_t)$ . The governing dynamics are assumed to be

$$
\frac{dB_t}{B_t} = rdt, \\
\frac{dS_t}{S_t} = \mu dt + \sigma dW_t.
$$

We define the portfolio $\pi$ as a control variable where $\pi_t \in \mathcal{F}_t$, the filtration generated by the Brownian motion. $\pi_t$ represents the fraction of wealth invested into the stock and hence $1-\pi_t$ is invested in the money-market. The value process associated to this portfolio is $(V^\pi_t)$. Its dynamics are simple as the portfolio's return is simply the portfolio-weighted sum of the stock return and money-market return:

$$
\frac{dV^\pi_t}{V^\pi_t} = \pi_t \frac{dS_t}{S_t} + (1-\pi_t) \frac{dB_t}{B_t}.
$$

This reduces to the controlled dynamical system:

$$
\frac{dV^\pi_t}{V^\pi_t} = [r+\pi_t (\mu-r)] dt + \pi_t \sigma dW_t.
$$

The risk neutral pricing formula can be derived in many ways. One derivation is from the following argument:

-   Find a measure $\mathbb{Q}$ such that $(\frac{S_t}{B_t})$ is a $\mathbb{Q}$ - martingale.

-   Since both $(\frac{S_t}{B_t})$ and $(\frac{B_t}{B_t} = 1)$ are $\mathbb{Q}$ - martingales, it is easy to show that any portfolio $\pi = (\pi_t)$ has a corresponding wealth process $V^\pi$ such that $(V^\pi_t/B_t)$ is also a $\mathbb{Q}$ - martingale.

-   Therefore $\mathbb{E}^\mathbb{Q} \left[ \frac{V^\pi_T}{B_T} \Big| \mathcal{F}_t \right] = \frac{V^\pi_t}{B_t}$ for all portfolios $\pi$.

-   Let $X$ be a time $T$ claim i.e. $X \in \mathcal{F}_T$ is paid out at time $T$. Then (since in this case every claim is attainable) there exists $\pi$ and $V^\pi_0$ such that $V^\pi_T = X$ almost surely. Therefore, from the replication and the $\mathbb{Q}$-martingality of all discounted portfolios, we get the risk neutral pricing formula:

$$\Pi(t;X) =\mathbb{E}^\mathbb{Q} \left[ \frac{X}{B_T/B_t} \Big| \mathcal{F}_t \right]$$

where the function $\Pi(t;\cdot)$ gives the price at time $t$.

For the first point, the measure $\mathbb{Q}$ can be found by finding the measure such that $W^\mathbb{Q}_t := W_t + \frac{\mu-r}{\sigma}t$ is a Brownian motion. Such a measure is given by the Girsanov theorem by defining $\mathbb{Q}$ by its Radon-Nikodym derivative w.r.t $\mathbb{P}$ to be

$$\frac{d\mathbb{Q}}{d\mathbb{P}} = \exp\left(-\frac{1}{2}\lambda^2T - \lambda W_T\right),$$ where $\lambda = \frac{\mu-r}{\sigma}$.

For the second point, it is simple to show $(V^\pi_t)$ is also a $\mathbb{Q}$ - martingale just by examining that $\frac{dV^\pi_t}{V^\pi_t} = \pi_t \frac{dS_t}{S_t} + (1-\pi_t) \frac{dB_t}{B_t}$. Since $B$ and $S$ are $\mathbb{Q}$-martingales, both $\frac{dS_t}{S_t}$ and $\frac{dB_t}{B_t}$ are driftless (in terms of $\mathbb{Q}$ dynamics) and so is $\frac{dV^\pi_t}{V^\pi_t}$. Of course you might say it is a local martingale, but if we restrict $\pi$ to a reasonable set of controls we will get that it is a martingale. We aren't too concerned about these details here for this intuitive example. This is discussed in [part 2](./logoptimal2.qmd).

This proves the pricing formula in this standard case.

# Continued Review: Pricing Under $\mathbb{P}$.

While the pricing formula under the risk neutral measure is both extremely useful and elegant, one might wonder how the option price relates to the true physical measure $\mathbb{P}$. After all, $\mathbb{P}$ represents the real world probabilities!

This can be easily done as

$$\mathbb{E}^\mathbb{Q} \left[ \frac{X}{B_T/B_t} \Big| \mathcal{F}_t \right] = \frac{\mathbb{E}^\mathbb{P}\left[ \frac{d\mathbb{Q}}{d\mathbb{P}} \frac{X}{B_T/B_t} \Big| \mathcal{F}_t \right]}{\mathbb{E}^\mathbb{P}\left[ \frac{d\mathbb{Q}}{d\mathbb{P}} \Big| \mathcal{F}_t \right]}.$$ Next, since $\frac{d\mathbb{Q}}{d\mathbb{P}} = \exp\left(-\lambda T - \frac{1}{2} \lambda^2 W_T\right)$, and also using $B_T/B_t = \exp(r(T-t))$, we get

$$\Pi(t;X) =\mathbb{E}^\mathbb{P} \left[ \frac{X}{e^{(r+\lambda)(T-t) + \frac{1}{2} \lambda^2 (W_T-W_t)}} \Bigg| \mathcal{F}_t \right],$$

which is the pricing under $\mathbb{P}$ adjusted with a new factor. What we have done is computed the so-called SDF, stochastic discount factor, explicitly. To be precise, we have found some $m_T \in \mathcal{F}_T$ such that

$$ \Pi(0;X) =\mathbb{E}^\mathbb{P} \left[ m_T X  \right], $$

$$\Pi(t;X) =\mathbb{E}^\mathbb{P} \left[ \frac{m_T}{m_t} X  \Big| \mathcal{F}_t \right]. $$ 

The interpretation is that the price of $X$ is its expected payout weighted by some appropriate kernel $m$ that accounts for both time and risk. For this reason, along with "stochastic discount factor", $m$ is also called the "pricing kernel".

This is all review at this point. We have shown that one can price a derivative under the physical measure by adjusting the derivative's payout for time and risk by taking its expectation weighted by the so-called SDF. However, on second glance, you may notice something interesting about this SDF. If you are familiar with the Merton problem or the continuous time Kelly Criterion, you may realize that the SDF is actually the recipricol of the "log optimal" or "Kelly optimal" portfolio! Is this a coincidence or is there something deeper going on here?

# Big Result

We will show that the pricing of the claim $X \in \mathbb{F}_T$ for the Black-Scholes model can be done as:

$$ \Pi(t;X) =  \mathbb{E}^\mathbb{P} \left[ \frac{X}{V^{\pi^*}_T/V^{\pi^*}_t} \Bigg| \mathcal{F}_t \right],$$

where $V^{\pi^*}$ is actually a portfolio given by the constant fraction allocation to stocks at all time: $\pi^*_t = \frac{\mu-r}{\sigma^2} = \frac{\lambda}{\sigma}$. 

The first observation we can make is that the SDF in this case reflects discounting the option's payout by the growth of 1 in a particular portfolio! This has huge implications. For example, one might naively and incorrectly think the options price should be the expectation of the bond-discounted payout of the option, i.e. $\mathbb{E}^\mathbb{P} \left[ \frac{X}{B_T/B_t} \Bigg| \mathcal{F}_t \right]$ This is wrong in that while it does correctly discount for time, it does not discount for the risk of the option. However, this approach turns out that it had a correct idea in mind: to discount the payout $X$ by an appropriate investable portfolio. So what is the correct portfolio that properly discounts options? Apparently the one corresponding to the allocation $\pi^*_t = \frac{\mu-r}{\sigma^2} = \frac{\lambda}{\sigma}$.


It turns out this is the so-called log optimal portfolio, which we will prove. The definition of this portfolio is $$ 
\pi^* = \arg \max_{\pi} \mathbb{E} [\log(V^\pi_T)]. 
$$, i.e. the portfolio control that maximizes expected log wealth. Such a control naturally maximizes the expected CAGR and therefore is called the "growth optimal" portfolio as well. The strategy that maximizes the growth rate is called the Kelly criterion, and hence why it is called the "Kelly optimal" portfolio as well.

## Simple verification

We will show that the portfolio $\pi^*_t = \frac{\mu-r}{\sigma^2} = \frac{\lambda}{\sigma}$ produces the portfolio value such that value$\frac{V^{\pi^*}_T}{V^{\pi^*}_t} = e^{(r+\lambda)(T-t) + \frac{1}{2} \lambda^2 (W_T-W_t)}$, which will prove $$\mathbb{E}^\mathbb{P} \left[ \frac{X}{V^{\pi^*}_T/V^{\pi^*}_t} \Bigg| \mathcal{F}_t \right] = \mathbb{E}^\mathbb{P} \left[ \frac{X}{e^{(r+\frac{1}{2}\lambda^2)(T-t) + \lambda (W_T-W_t))}} \Bigg| \mathcal{F}_t \right] = \Pi(t;X)$$ as desired. This is simple manner of substitution as we have:

$$
\frac{dV^{\pi^*}_t}{V^{\pi^*}_t} = [r+\pi^*_t (\mu-r)] dt + \pi^*_t \sigma dW_t.
$$ Now, inputting $\pi^*_t = \frac{\mu-r}{\sigma^2} = \frac{\lambda}{\sigma}$, we see

$$
\frac{dV^{\pi^*}_t}{V^{\pi^*}_t} = (r + \lambda^2) dt + \lambda dW_t.
$$ This is a simple geometric Brownian motion:

$$V^{\pi^*}_T = V^{\pi^*}_t \exp\left( (r + \frac{1}{2} \lambda^2)(T-t) + \lambda (W_T - W_t)\right),$$

and hence the result holds.

## Log optimality of the portfolio

We can show that the portfolio is the so-called log-optimal portfolio in two different ways. I'll start with my favorite approach which doesn't involve a direct computation, but uses the fact that we have just shown it to be the pricing kernel. We must find the portfolio $\pi^*$ such that:

$$ 
\pi^* = \arg \max_{\pi} \mathbb{E} [\log(V^\pi_T)]. 
$$

### Indirect Proof

We already have shown that that the portfolio $\pi^*_t = \frac{\mu-r}{\sigma^2} = \frac{\lambda}{\sigma}$ produces the portfolio value such that value$\frac{V^{\pi^*}_T}{V^{\pi^*}_t} = e^{(r+\lambda)(T-t) + \frac{1}{2} \lambda^2 (W_T-W_t)}$ and thus $$
\Pi(t;X) =   \mathbb{E}^\mathbb{P} \left[ \frac{X}{V^{\pi^*}_T/V^{\pi^*}_t} \Bigg| \mathcal{F}_t \right].
$$ At this point, we haven't yet shown this $\pi^*$ is log-optimal, but we know the pricing formula is true from our previous work. Now we let $\pi$ be an arbitrary portfolio. Assume $V^\pi_0 = V^{\pi^*}_0$ meaning that they start with the same initial amount. By the pricing formula, we can "price" the portfolio:

$$
\Pi(t;V^\pi_t) = V^\pi_t =   \mathbb{E}^\mathbb{P} \left[ \frac{V^\pi_T}{V^{\pi^*}_T/V^{\pi^*}_t} \Bigg| \mathcal{F}_t \right].
$$ which gives in particular at $t=0$

$$
1  =  \frac{V^\pi_0}{V^{\pi^*}_0} =  \mathbb{E}^\mathbb{P} \left[ \frac{V^\pi_T}{V^{\pi^*}_T} \right].
$$

Now taking $\log(\cdot)$ of both sides, and applying Jensen's inequality, we get

$$    \mathbb{E}^\mathbb{P} \left[ \log \left( \frac{V^\pi_T}{V^{\pi^*}_T}\right)\right] \leq \log \left( \mathbb{E}^\mathbb{P} \left[ \frac{V^\pi_T}{V^{\pi^*}_T} \right] \right)  = 0, $$ and hence we conclude that $$
\mathbb{E}^\mathbb{P} \left[ \log \left( V^\pi_T\right)\right] \leq \mathbb{E}^\mathbb{P} \left[ \log \left( V^{\pi^*}_T\right)\right], \ \forall \pi = (\pi_t)_t.
$$ In otherwords, $\pi^*$ is the log-optimal portfolio!

What we have shown is that if a portfolio has the so-called "numeraire-property" for $\mathbb{P}$, then it is log-optimal. Here, the "numeraire-property" means that it is the choice of numeraire such that every asset becomes a $\mathbb{P}$ martingale in units of this numeraire.

Since our considered portfolio (which we didn't yet know was log-optimal), was known to have the numeraire-property for $\mathbb{P}$, we concluded that it was necessarily log-optimal. Surprisingly, we have proven the exact form of the log-optimal portfolio without even constructing it explicitly!

For those more interested in this property, we note that this can be generalized to supermartingale numeraires. That is if a portfolio is such that asset prices in units of this numeraire portfolio are all supermartingales, then it is necessarily log-optimal. While in more general settings, a portfolio with the martingale numeraire property may not exist, a portfolio with the supermartingale numeraire property always exist. Moreover, a supermartingale numeraire portfolio must be log-optimal due to this same Jensen's inequality argument.



### Construction

Another approach to showing that $\pi^* = \frac{\mu-r}{\sigma^2}$ gives the log-optimal portfolio is through direct construction. We don't need to do this since we already have a fun, clever proof, but I have a fun way to do this as well.

A typical approach is to solve the stochastic optimal control problem via the Hamilton-Jacobi-Bellman equation. This is actually overkill for this problem and it is very easy to derive from a direct computation. Simply, lets compute $\mathbb{E} [\log(V^\pi_T)]$ for an arbitrary portfolio $(\pi_t)_t$. We have that for any admissible $(\pi_t)_t$:

$$
\frac{dV^{\pi}_t}{V^{\pi}_t} = [r+\pi_t (\mu-r)] dt + \pi_t \sigma dW_t.
$$ This has the solution

$$V^\pi_T = V^\pi_0\exp \left( \int_0^T [r+\pi_t (\mu-r) - \frac{1}{2} \sigma^2 \pi_t^2 ] dt  + \int_0^T \pi_t \sigma dW_t \right).$$

Taking $\log$ and the expectation, we get:

$$\mathbb{E}[\log(V^\pi_T)] = \log(V^\pi_0) +  \mathbb{E} \left[ \int_0^T [r+\pi_t (\mu-r) - \frac{1}{2} \sigma^2 \pi_t^2 ] dt \right].$$ Now, we seek to maximize the above expression. This may seem non-trivial at first, but carefully inspecting, we see the integrand is just a constant coefficient degree $2$ polynomial in $\pi_t$. This can be maximized pointwise for all $t$ and $\omega$. Maximizing the integrand, we have $\pi_t = \frac{\mu-r}{\sigma^2}$ as claimed.

In case one is suspect of this maximization, we can note that

$$ 
r+ (\mu-r)\pi_t(\omega)  - \frac{1}{2} \sigma^2 \pi_t(\omega)^2   \leq r + (\mu-r) \left( \frac{\mu-r}{\sigma^2} \right)   - \frac{1}{2} \left( \frac{\mu-r}{\sigma^2}
\right)^2,
$$

by the optimization of a second degree polynomial as $\pi_t(\omega) \in \mathbb{R}$, so the bound holds pointwise for all $t$ and $\omega$.


Thus taking integral and expectation over the inequality, we get $$ 
\mathbb{E} \left[ \int_0^T [ r+ (\mu-r)\pi_t(\omega)  - \frac{1}{2} \sigma^2 \pi_t(\omega)^2 ] dt \right]  \leq \mathbb{E} \left[ \int_0^T [ r + (\mu-r) \left( \frac{\mu-r}{\sigma^2} \right)   - \frac{1}{2} \left( \frac{\mu-r}{\sigma^2}\right)^2 ]dt \right].
$$

Since $\pi_t = \frac{\mu-r}{\sigma^2}$ is an admissible portfolio (i.e. an allocation strategy that can actually be put into practice), we see that the bound is attained by this $\pi$ and hence it is optimal.

Thus, we have that $\pi_t = \pi^*_t = \frac{\mu-r}{\sigma^2}$ is the log-optimal portfolio.

# Summary

We have shown for this simple Black-Scholes model, that the option pricing for the time $T$ claim $X \in \mathcal{F}_T$ is given by

$$ \frac{\Pi(t;X)}{V^{\pi^*}_t} =  \mathbb{E}^\mathbb{P} \left[ \frac{X}{V^{\pi^*}_T} \Bigg| \mathcal{F}_t \right],$$ where $\pi^* = (\pi^*_t)_t$ is the log-optimal portfolio meaning that it maximizes over all portfolios, the quantity $\mathbb{E}[ \log(V^{\pi^*}_T)]$. This portfolio is also called the growth-optimal portfolio or Kelly optimal as it is the portfolio that satisfies the Kelly criterion and maximizes the portfolios growth rate i.e. it maximizes the expected CAGR. It has a number of wonderful properties, which can be covered later.

The interpretation of the above pricing is as follows: we have the remarkable relation that if the units of measurement were not currency, but instead of log-optimal portfolio value, then the price of an option is just its expected payout under the true measure $\mathbb{P}$!

Is this just a coincidental feature of the Black-Scholes model for stock dynamics or is this a greater truth? Let's find out in [part 2](./logoptimal2.qmd)!
