---
title: "Overview"
---

# Introduction

We first introduce a general model and define the growth optimal portfolio associated to it. Such a portfolio can be also called Kelly or log optimal.

First we define $S^i_t$ to be the total return process of asset $i$. This is so that dividends can be ignored. When we have options on the stock price and not the total return process, we can adjust as needed.

We start by defining a filtration $\mathcal{F}_t$ which represents the information in the market up to and including time $t$. We then have

$$dS^i_t = \mu^i_t dt + \sum_{j=1}^M \sigma^{i,j}_t dW^j_t.$$ for each $i \in \{1, \cdots, N\}$ and also $$dB_t = r_t B_tdt$$ for the money market account.

It is important to note that $\mathcal{F}_t$ is not the filtration generated by the Brownian motion, but one that contains it. $\mu_t$, $\sigma_t$, $r_t$ are adapted to the filtration $\mathcal{F_t}$ -- not just the Brownian motion. This means that they can depend on some outside information. This includes for instance, a stochastic volatility model as well as any others.

Then generality of this model holds from the generality of $\mu_t$, $\sigma_t$, and $r_t$. This allows for multiple sources of noise (so for instance we can think of APT models) and stochastic volatility.The model considered (HERE) for instance considers earnings and price to earnings multiple as exogenous processes and the stock price process is determined from these two. This would still fit in to this model. The reason the model maybe unrealistic is that it assumes that we actually do know the local mean rates of returns and volatilities at a given time having observed the information up and to this time.

Now, we define a portfolio $\pi_t = (\pi^1_t , \cdots, \pi^N_t)$ which is a process adapted to $\mathcal{F}_t$. We think of this portfolio in terms of the fraction of wealth allocated to each asset (intuitively: think $\pi_t$ represents the percentage allocations). The money market allocation will be $1 - \sum_i \pi^i_t$, so that way no additional portfolio constraints must be introduced. With this notation, it is very easy to define self financing portfolios. It just corresponds to any choice of $\pi_t = (\pi^1_t , \cdots, \pi^N_t) \in \mathbb{R}^N$ (we may want to choose a bounded set so things do not explode -- this corresponds to leverage constraints). The self-financing portfolio associated to $\pi$, $V^\pi$, is easily represented in terms of portfolio return:

$$\frac{dV_t^\pi}{V_t^\pi} = \sum_{i=1}^N \pi^i_t \frac{dS^i_t}{S^i_t} + (1-\sum_{i=1}^N \pi^i_t) r_t dt$$

which gives

$$\frac{dV_t^\pi}{V_t^\pi} = \pi_t^T \mu_t dt + \pi_t^T \sigma_t dW_t + (1-\sum_{i=1}^N \pi^i_t) r_t dt$$

where $\mu = (\mu^1 , \cdots, \mu^N)$ and $\sigma = (\sigma^{i,j})_{i,j}$. Without loss of generality, we take $V_0^\pi = 1$ unless stated otherwise.

We now can define the log-optimal portfolio as the argument maximizer out of admissible portfolio processes, $(\pi_t)$, of the expression

$$\mathbb{E}[\log(V_t^\pi)].$$

# Theorems



> **Theorem 1** Assume that the claim $\xi$ is attainable. Then its unique arbitrage price is given by $$\frac{\Pi(t ; \xi)}{V^{\pi^*}_T} = \mathbb{E}^{\mathbb{P}}\left[ \frac{\xi}{V^{\pi^*}_T} \bigg{|} \mathcal{F}_t \right] $$ That is, the log-optimal portfolio process is the appropriate numeraire such that option pricing is simply the true expected value (under the real world measure $\mathbb{P}$!) In other words, if the units of account were simply not dollars, or not bank account, but instead units of log-optimal portfolio, we could simply understand option pricing in the most naive way possible (the expectation of the payout under the true measure)... and it would turn out to be right!

These results are somewhat known but surprisingly somewhat unknown. Theorem 2 in particular. One can do options pricing without realizing that Theorem 2 provides an alternative method all along for very general models and very general attainable claims.

Lastly, the problem with Theorem 2 is that $\xi$ needs to be attainable. But what if $\xi$ is generally unattainable as would be the case for generic claims in a model when $M > N$ for instance when there are more noises than assets. This is a real world setting. However, we can borrow from utility theory. The idea is that although a claim cannot be hedged, its marginal addition to a portfolio would either add or remove utility for a given investor. This investor (identified by their utility function) has a price of the option such that the marginal utility associate with the addition of the option is $0$. This would be the investor's utility price for the option.

To make this more rigorous:

> ** Definition 1 ** Consider a claim that pays out $\xi_T$ at time $T$. Let $(U_\alpha,T)$ be the investor's utility function (indexed by $\alpha$) for horizon $T$. This means that the investor selects a portfolio strategy $\pi(\alpha)$ such that $\mathbb{E}[ U_\alpha(V^\pi_T)]$ is maximized.
>
> Then the price $\xi_0(\alpha)$, called investor $(U_\alpha,T)$'s indifference price for a marginal quantity, satisfies: $$\frac{d}{d\epsilon} \bigg{|}_{\epsilon = 0} \mathbb{E}\bigg[ U_\alpha \left( (1-\epsilon)V^{\pi(\alpha)}_T + \epsilon \frac{\xi_T}{\xi_0(\alpha)} \right) \bigg] = 0.$$
>
> This can be reduced and we write $$\xi_0(\alpha) = \frac{\mathbb{E}\bigg[ U_\alpha ' \left( V^{\pi(\alpha)}_T \right) \xi_T \bigg]}{\mathbb{E}\bigg[ U_\alpha ' \left( V^{\pi(\alpha)}_T \right) V^{\pi(\alpha)}_T \bigg] }.$$

Now we have the very powerful result.

> **Theorem 2** Let $(U_\gamma,T)$ be the investor's utility function for time horizon $T$. In this case we take $U_\gamma$ to be any CRRA utility function $U_\gamma(x) = \gamma x^\gamma$ for $\gamma < 1$. We claim that $\xi_0(\gamma)$ does not depend on $\gamma$ and moreover,

$$\chi_0(\alpha) = \chi_0 = \mathbb{E}^{\mathbb{P}}\left[ \frac{\chi_T}{V^{\pi^*}_T} \right].$$
