---
title: " Log-Optimal And Risk Neutral Valuation -- The General Case"
---
In [part 1](.logoptimal1.qmd), we had derived the result:

$$
\frac{\Pi(t,X)}{V^{\pi^*}_t} = \mathbb{E}^\mathbb{P} \left[ \frac{X}{V^{\pi^*}_T} \bigg| \mathcal{F}_t\right],
$$
that is the time $t$-price of the attainable claim $X$ in units of log-optimal portfolio value is merely the expected value (under $\mathbb{P}$) of the payout of $X$ in units of log-optimal portfolio at the expiration time! In otherwords, the log-optimal portfolio properly discounted for both time and risk such that a naive pricing under the physical measure holds!

Now, we show this result is actually quite general! We will consider certain general market dynamics for the case of a market with many assets, and we show that all claims that are attainable in this market have an arbitrage pricing formula that is consistent with the above pricing equation! 


# Problem Set-up
- We consider $I$ assets with price dynamics affected by $J$ noises. In reality, $J>>I$ as there are many more noises than assets, and we will take this to be the case.

- Asset $i$'s dynamics are given by

$$ 
\frac{dS^i_t}{S^i_t} = \mu^i_t dt + \sum_{j=1}^J \sigma^{ij}_t dW^j_t
$$

- $\mu^i_t$ is the mean rate of return of asset $i$ which itself is potentially stochastic. 

- $\sigma^{ij}_t$ is the noise $j$-specific volatility of asset $i$. For example, if noise $j$ represents the socks due to interest rates then $\sigma^{ij}_t$ represents the sensitivity of $i$ to these changes in interest rates. It itself is also potentially stochastic. 

- Lastly there is an interest rate $r_t$ for a money-market account which is also potentially stochastic.

- We will use the notation $\sigma_t = (\sigma^{ij}_t)$ and $\mu_t = (\mu^1_t, \cdots, \mu^I_t)$.

- To be precise, we have $\sigma_t,r_t,\mu_t$ are all $\mathcal{F}_t$-adapted where $\mathcal{F}_t$ is the sigma algebra generated by the Brownian motion $W_t = (W^1_t, \cdots, W^J_t)$. At first this seems restrictive, we would want them to be generally random beyond just the filtration generated by the Brownian motion! However, there is a trick here. At first glance, one might not think stochastic volatility, for example, is included in this model as the volatility is not adapted to the Brownian motion of the stock. However, for stochastic volatility, we would merely need to do $\frac{dS_t}{S_t} = \mu dt + \sigma_t dW^1_t + 0 dW^2_t$ and $\sigma_t$'s dynamics are given in terms of $W^2_t$. Thus it is not adapted to the "Brownian motion" of the stock, but it is $\mathcal{F}_t$ adapted which allows us to do stochastic integration, etc.. Thus actually the condition that $\sigma_t,r_t,\mu_t$ are all $\mathcal{F}_t$-adapted can lead to very broad models. Essentially by making $J$ very large, we are including many many sources of noise. Many of these noises may not be noise terms for the asset prices but noise terms for the interest rate, mean returns, and volatilities with respect to given asset-specific noises.

- Now we consider a portfolio which invests the fraction of wealth $\pi^i_t$ into asset $i$ at time $t$. 

- We say $\pi = (\pi^1, \cdots, \pi^I)$ are the proportions of wealth invested in each asset leaving $1 - \pi_t^T \vec{1}$ is invested into the money market at time $t$. Note that we do not distinguish vectors and scalars with a notation other than the case with $1$ vs $\vec{1}$.

- The portfolio process associated to $\pi$ we call $V^\pi_t$ and it is described through its return:

$$
\frac{dV^\pi_t}{V^\pi_t} = \sum_{i=1}^n \pi^i_t \frac{dS^i_t}{S^i_t} + (1 - \pi_t^T \vec{1})r_t dt,
$$

which can be written as

$$
\frac{dV^\pi_t}{V^\pi_t} = [r_t + \pi_t^T(\mu_t - \vec{1}r_t)]dt +  \pi_t^T \sigma_t dW_t.
$$

- **Technical requirements**: We require $\pi^i_t$ be $\mathcal{F}_t$-adapted and bounded, i.e. $|\pi_t| \leq K$ for all $t$. We also require that  $\sigma_t,r_t,\mu_t$ are defined such that they are almost surely bounded and the covariance matrix $(\sigma_t\sigma_t^T)$ is non-singular and that its minimal eigenvalue is uniformly bounded (for all $t$) by some $\epsilon > 0$. These technical conditions ensure that the driftless expressions we will later consider are not strict local martingales but rather martingales. The proof is given in @sec-locmg.





# Numeraire Portfolio

We now wish to price any attainable time $T$ claim $X$. We know that since $(\sigma_t\sigma_t^T)$ is invertible, we have no arbitrage. From the standard theory, we do not have attainability of arbitrary claims (as $J > I$), but we can price any attainable claim $X$ with any choice of the infinitely many risk neutral measures. The result is
$$
\Pi(t;X) = \mathbb{E}^\mathbb{Q} \left[ \frac{X}{B_T/B_t} \Big| \mathcal{F}_t \right]
$$
where $(B_t)$ is the price process associated to a $100\%$ money-market allocation, i.e. $\frac{dB_t}{B_t} = r_t dt$. This holds where $\mathbb{Q}$ is a measure such that $\frac{S^i_t}{B_t}$ are $\mathbb{Q}$-martingales for all $i \in \{1, \cdots, I\}$. The reasoning is that since all stocks and bonds are $\mathbb{Q}$-martingales, it is easy to show that any portfolio is also a $\mathbb{Q}$-martingales and hence any attainable claim is a $\mathbb{Q}$-martingale. 

Thus given a model, in order to price attainable claims, one would have to construct a $\mathbb{Q}$ such that all stocks are $\mathbb{Q}$ martingales.

There is a secondary approach, however. What if instead of finding a measure $\mathbb{Q}$ (one of infinitely many) such that all portfolio values are $\mathbb{Q}$-martingales, what if we instead find a numeraire such that all portfolio values are $\mathbb{P}$ martingales with respect to this numeraire? Of course such a numeraire exists as it corresponds to any of the EMMs $\mathbb{Q}$. However, what if there exists a numeraire that is the wealth process associated to a portfolio $\tilde{\pi}$? If such a portfolio $\tilde{\pi}$ exists, then for all attainable time $T$ claims $X$, we will have 

$$
\Pi(t;X) = \mathbb{E}^\mathbb{P} \left[ \frac{X}{V^{\tilde\pi}_T/V^{\tilde\pi}_t} \Bigg| \mathcal{F}_t \right]
$$
from a trivial replicating argument.  At first, we must ask if this is even possible. We show that it is indeed possible, and we do this by constructing such a portfolio.



## Constructing the numeraire portfolio

We can try to find such a numeraire portfolio $\tilde{\pi}$, i.e. a portfolio such that $\left( V_t^\pi/V_t^{\tilde{\pi}} \right)_t$ is a $\mathbb{P}$ martingale for all portfolios $\pi$ by demanding that $d\left( V_t^\pi/V_t^{\tilde{\pi}} \right)$ is driftless. Equivalently, we require $\frac{d\left(V_t^\pi/V_t^{\tilde{\pi}} \right)}{V_t^\pi/V_t^{\tilde{\pi}}}$ is driftless. (Note this is the portfolio $\pi$'s return in units of $V_t^{\tilde{\pi}}$ which will be useful to compute. As a general trick, when working with a portfolio process, it is often easiest to work in terms of its return. When working with a ratio of assets, the ratio represents the price of one in terms of units of the other and thus itself represents a price process. When working with this new price process it is often useful to work in terms of its return.) 

Now let's construct the numeraire portfolio. We wish to find $\tilde{\pi}$ such that for all $\pi$, we have 

$$\frac{d\left(V_t^\pi/V_t^{\tilde{\pi}} \right)}{V_t^\pi/V_t^{\tilde{\pi}}}$$
is driftless. Hence $(V_t^\pi/V_t^{\tilde{\pi}})$ will be a $\mathbb{P}$ martingale as we have ensured these driftless relative portfolio values are not just local martingales, but martingales by imposing technical requirements and will be proven in @sec-locmg.

First, by Ito's lemma, we have

$$\frac{d\left(V_t^\pi/V_t^{\tilde{\pi}} \right)}{V_t^\pi/V_t^{\tilde{\pi}}} = \frac{dV^\pi_t}{V^\pi_t} - \frac{dV^\tilde\pi_t}{V^\tilde\pi_t} +  \left(\frac{dV^\tilde\pi_t}{V^\tilde\pi_t} \right)^2 - \frac{dV^\tilde\pi_t dV^\pi_t}{V^\tilde\pi_t V^\pi_t}.$$

The surprising cleanliness of the above equation is due to the fact that we are working with a highly relevant quantity -- the return of one portfolio in units of another (or the relative return). Substituting for the portfolio returns and factoring, we have


$$\frac{d\left(V_t^\pi/V_t^{\tilde{\pi}} \right)}{V_t^\pi/V_t^{\tilde{\pi}}} = (\pi_t - \tilde{\pi}_t)^T \left((\mu_t - \vec{1}r_t) dt + \sigma_t dW_t - \sigma_t \sigma_t^T \tilde{\pi_t} dt\right) .$$

Thus it is driftless if and only if 

$$ (\pi_t - \tilde{\pi}_t)^T \left((\mu_t - \vec{1}r_t)  - \sigma_t \sigma_t^T \tilde{\pi_t}\right) = 0.$$

We need to find a $\tilde{\pi}$ such that the above holds for all $\pi$. This can be done for each $t$. Denote $x=\pi_t$, $y=\tilde{\pi}_t$, $b = (\mu_t - \vec{1}r_t)$ and $A = \sigma_t \sigma_t^T$. We note that by our original assumptions, $A$ is invertible.

We now have the problem find $y$ such that for all $x$ it holds:

$$
(x-y)^T(b-Ay) = 0.
$$
First, since $A$ is invertible, we can choose $y = A^{-1}b$ and we are done. However, one might wonder about uniqueness. This $y$ is infact unique as the above has to hold for all $x$. We can choose the particular choice $x = b - Ay + y$ which shows that $||b-Ay||^2 = 0$ and hence $y = A^{-1}b$ is the only solution. What this means is that

 $$\tilde{\pi}_t =  (\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t)$$ 
 is the only numeraire portfolio.

This shows that when the problem is arbitrage free, there exists a unqiue numeraire portfolio $\tilde{\pi} =  (\sigma_t \sigma_t^T)^{-1}  (\mu_t - \vec{1}r_t)$. With this portfolio we have, $\left( V_t^\pi/V_t^{\tilde{\pi}} \right)_t$ is a $\mathbb{P}$ martingale for all portfolios $\pi$ which gives the relation of all portfolios:

$$
\frac{V^\pi_t}{V^{\tilde\pi}_t} = \mathbb{E}^\mathbb{P} \left[ \frac{V^\pi_T}{V^{\tilde\pi}_T} \Bigg| \mathcal{F}_t \right]
$$


and hence for all attainable claims
$$
\Pi(t;X) = \mathbb{E}^\mathbb{P} \left[ \frac{X}{V^{\tilde\pi}_T/V^{\tilde\pi}_t} \Bigg| \mathcal{F}_t \right].
$$
This portfolio turns out to be the log-optimal portfolio. This is easily seen as taking $V^\pi_0 = V^{\tilde\pi}_0$ (i.e. the portfolio values start with the same initial wealth), we have 

$$
1 = \mathbb{E}^\mathbb{P} \left[ \frac{V^\pi_T}{V^{\tilde\pi}_T} \right].
$$

Taking log and applying Jensen's inequality will give that 

$$
  \mathbb{E}^\mathbb{P} \left[\log(V^\pi_T)\right] \leq \mathbb{E}^\mathbb{P} \left[\log(V^{\tilde{\pi}}_T) \right], \quad \forall \pi,
$$
hence the numeraire portfolio is the log-optimal portfolio. In our notation, this means that $\tilde{\pi} = \pi^*$. 

## Martingality of the Driftless Processes (Avoiding the Strict Local MG) {#sec-locmg}

In our proof, we assumed that a driftless process was a martingale. However, we need to be careful here since driftless processes are only local martingales in general. In this case, we will show it is a martingale because of our demanded regularity conditions on our model and admissible portfolios.

Specifically, we had that

$$\frac{d\left(V_t^\pi/V_t^{\tilde{\pi}} \right)}{V_t^\pi/V_t^{\tilde{\pi}}} = (\pi_t - \tilde{\pi}_t)^T \left((\mu_t - \vec{1}r_t) dt + \sigma_t dW_t - \sigma_t \sigma_t^T \tilde{\pi_t} dt\right), $$

 is driftless when

$$ (\pi_t - \tilde{\pi}_t)^T \left((\mu_t - \vec{1}r_t)  - \sigma_t \sigma_t^T \tilde{\pi_t}\right) = 0,$$

which occurs only for

$$\tilde{\pi}_t =  (\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t).$$ 

We will now show this driftless expression is not just a local martingale, but a full martingale. 

With this $\tilde{\pi}$, we have that for all $\pi$

\begin{align}
\frac{d\left(V_t^\pi/V_t^{\tilde{\pi}} \right)}{V_t^\pi/V_t^{\tilde{\pi}}} & = (\pi_t - \tilde{\pi}_t)^T \left((\mu_t - \vec{1}r_t) dt + \sigma_t dW_t - \sigma_t \sigma_t^T \tilde{\pi_t} dt\right) \\
 & = (\pi_t - (\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t) )^T \sigma_t dW_t.
\end{align}

Now since we are assuming $\mu_t$, $r_t$, $\sigma_t$ are uniformly bounded for all $t,\omega$, and the positive uniform lower bound for the eigenvalue of $(\sigma_t \sigma_t^T)$, we get

$$||(\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t)|| \leq ||(\sigma_t \sigma_t^T)||^{-1}_{op} ||(\mu_t - \vec{1}r_t)|| \leq K_1.$$

Similarly, since we consider all portfolios of finite leverage, i.e. we have that $||\pi_t|| \leq K_2$ for all $t$, so we have:

$$
||(\pi_t - (\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t) )^T \sigma_t || \leq K.
$$
Thus we see that 

$$\mathbb{E}\left[ e^{\frac{1}{2} \int_0^T ||(\pi_t - (\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t) )^T \sigma_t ||^2 dt} \right] \leq \mathbb{E}\left[ e^{\frac{1}{2} K^2 T }\right] < \infty.$$

This is Novikov's condition which guarantees that the process satisfying
$$\frac{d\left(V_t^\pi/V_t^{\tilde{\pi}} \right)}{V_t^\pi/V_t^{\tilde{\pi}}}  =  (\pi_t - (\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t) )^T \sigma_t dW_t$$
i.e.

$$
V_t^\pi/V_t^{\tilde{\pi}} = \exp \left( \frac{1}{2} \int_0^T ||(\pi_t - (\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t) )^T \sigma_t ||^2 dt + \int_0^T(\pi_t - (\sigma_t \sigma_t^T)^{-1} (\mu_t - \vec{1}r_t) )^T \sigma_t dW_t \right)
$$
is a martingale for all $t \in [0,T]$. 


# A remark on non-uniqueness of the EMM

In our case, we have an incomplete market. However, we can price an attainable claim with one of the infinitely many EMMs $\mathbb{Q}$. Why then was the numeraire portfolio unique?

Indeed there are infinitely many EMM $\mathbb{Q}$, and hence there are infinitely many stochastic discount factors (SDFs) defined by  $m_T = \frac{d\mathbb{Q}}{d\mathbb{P}} \Big|_\mathcal{F_t} \frac{1}{B_T/B_t}$ that can be used as a kernel to price claims under $\mathbb{P}$. However only one out of these SDFs corresponds to a portfolio. That is there exists a unique $\mathbb{Q}$ (out of the set of all risk neutral measures for this model) such that 
$\frac{d\mathbb{Q}}{d\mathbb{P}} \Big|_\mathcal{F_t} \frac{1}{B_T/B_t} = \frac{1}{V^{\tilde{\pi}}_T/V^{\tilde{\pi}}_t}$, and only when $V^{\tilde{\pi}}$ corresponds to the value of the log-optimal portfolio.

# Conclusion

We see that for attainable claims, the log-optimal portfolio allows us to price under $\mathbb{P}$ in a surprising way: when everything is in units of log-optimal portfolio, we have that the price of the claim is just its expected payout under $\mathbb{P}$!

In a way, the most naive (and wrong) options valuation approach is actually correct when the *right* units of "value" are taken into account! This result is so beautiful, one might ask if it's truth exists beyond arbitrage pricing. Can this play a role in pricing non-attainable claims? For this, you can read [part 3](./logoptimal3.qmd).